#include "time_series_model.h"

/* 
 * This is the entry point function generated by onnx2c.
 * It expects input as a 2D array [1][1] and outputs to a 2D array [1][1].
 */
extern void entry(const float input[1][1], float output[1][1]);

void time_series_model_init(void) {
    /* No initialization needed for this model */
}

void time_series_model_run(const float* input_data, float* output_data) {
    /* 
     * The entry function expects 2D arrays, but our API uses simple pointers.
     * We need to reshape the data accordingly.
     */
    float input_reshaped[1][1] = {{*input_data}};  /* Convert single value to 2D array */
    float output_reshaped[1][1];
    
    /* Call the generated model function */
    entry(input_reshaped, output_reshaped);
    
    /* Copy the result back to the output pointer */
    *output_data = output_reshaped[0][0];
}

void time_series_model_terminate(void) {
    /* No cleanup needed for this model */
}